eval.batch_size: 2
eval.cutoff_len: 1024
eval.dataset:
- mix_eval
eval.dataset_dir: data
eval.max_new_tokens: 512
eval.max_samples: '100000'
eval.output_dir: eval_2025-03-20-13-21-52
eval.predict: true
eval.temperature: 0.1
eval.top_p: 0.7
top.booster: auto
top.checkpoint_path:
- train_2025-03-19-20-37-51
top.finetuning_type: lora
top.model_name: DeepSeek-R1-1.5B-Distill
top.quantization_bit: none
top.quantization_method: bitsandbytes
top.rope_scaling: none
top.template: deepseek3
