adapter_name_or_path: saves\DeepSeek-R1-1.5B-Distill\lora\train_2025-03-19-20-37-51
cutoff_len: 1024
dataset_dir: data
do_predict: true
eval_dataset: mix_eval
finetuning_type: lora
flash_attn: auto
max_new_tokens: 512
max_samples: 100000
model_name_or_path: D:\kings\prj\Finetune_local\models-origin\models--deepseek-ai--DeepSeek-R1-Distill-Qwen-1.5B\snapshots\ad9f0ae0864d7fbcd1cd905e3c6c5b069cc8b562
output_dir: saves\DeepSeek-R1-1.5B-Distill\lora\eval_2025-03-20-13-21-52
per_device_eval_batch_size: 2
predict_with_generate: true
preprocessing_num_workers: 16
quantization_method: bitsandbytes
stage: sft
temperature: 0.1
template: deepseek3
top_p: 0.7
trust_remote_code: true
